version: 0.0
os: linux
files:
  - source: awscodedeploy/var/www/localhost/htdocs/
    destination: /var/www/html
hooks:
  ApplicationStop:
    - location: scripts/stopServer.sh
  BeforeInstall:
    - location: scripts/installApp.sh
      runas: ec2-user
  ApplicationStart:
    - location: scripts/startServer.sh
      timeout: 300
